/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AboutPage: typeof import('./src/components/AboutPage.vue')['default']
    App: typeof import('./src/components/App.vue')['default']
    BoardSelector: typeof import('./src/components/BoardSelector.vue')['default']
    BoardSelectorCard: typeof import('./src/components/BoardSelectorCard.vue')['default']
    BunchingEffect: typeof import('./src/components/BunchingEffect.vue')['default']
    DbItemPicker: typeof import('./src/components/DbItemPicker.vue')['default']
    LoadResultPage: typeof import('./src/components/LoadResultPage.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    RangeEditor: typeof import('./src/components/RangeEditor.vue')['default']
    RangeMiniViewer: typeof import('./src/components/RangeMiniViewer.vue')['default']
    ResultBasics: typeof import('./src/components/ResultBasics.vue')['default']
    ResultChance: typeof import('./src/components/ResultChance.vue')['default']
    ResultCompare: typeof import('./src/components/ResultCompare.vue')['default']
    ResultGraphs: typeof import('./src/components/ResultGraphs.vue')['default']
    ResultMiddle: typeof import('./src/components/ResultMiddle.vue')['default']
    ResultNav: typeof import('./src/components/ResultNav.vue')['default']
    ResultTable: typeof import('./src/components/ResultTable.vue')['default']
    ResultViewer: typeof import('./src/components/ResultViewer.vue')['default']
    RunSolver: typeof import('./src/components/RunSolver.vue')['default']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
    TreeConfig: typeof import('./src/components/TreeConfig.vue')['default']
    TreeEditor: typeof import('./src/components/TreeEditor.vue')['default']
  }
}
