name: Build and Upload Artifacts

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, ubuntu-20.04]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Setup Rust nightly
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rust-src

      - name: Install dependencies (Linux)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev librsvg2-dev

      - name: Install app dependencies
        run: npm ci

      - name: Build the app (Windows)
        if: matrix.platform == 'windows-latest'
        run: npm run tauri build -- --target x86_64-pc-windows-msvc -- -Z build-std=std,panic_abort -Z build-std-features=panic_immediate_abort

      - name: Build the app (Linux)
        if: matrix.platform == 'ubuntu-20.04'
        run: npm run tauri build -- --target x86_64-unknown-linux-gnu -- -Z build-std=std,panic_abort -Z build-std-features=panic_immediate_abort

      - name: Upload Windows artifacts
        if: matrix.platform == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: desktop-postflop-windows-${{ github.run_number }}
          path: |
            src-tauri/target/x86_64-pc-windows-msvc/release/Desktop Postflop.exe
            src-tauri/target/x86_64-pc-windows-msvc/release/bundle/msi/Desktop Postflop_*_x64_en-US.msi
          retention-days: 90

      - name: Upload Linux artifacts
        if: matrix.platform == 'ubuntu-20.04'
        uses: actions/upload-artifact@v4
        with:
          name: desktop-postflop-linux-${{ github.run_number }}
          path: |
            src-tauri/target/x86_64-unknown-linux-gnu/release/bundle/deb/desktop-postflop_*_amd64.deb
            src-tauri/target/x86_64-unknown-linux-gnu/release/bundle/appimage/desktop-postflop_*_amd64.AppImage
          retention-days: 90
